[package]
name = "bittorrent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bencode = { git = "https://github.com/hiperion14/bencode.git" }
url = "2.2"
bytes = ">1.0"
rand = "0.8"
sha1 = ">0.6"